export default [
  {
    "recipe": "Iron Plate",
    "output": "Iron Plate",
    "outputQtyPerMin": 2,
    "item1": "Iron Ingot",
    "item1Qty": 3,
    "item2": null,
    "item2Qty": null,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Iron Rod",
    "output": "Iron Rod",
    "outputQtyPerMin": 1,
    "item1": "Iron Ingot",
    "item1Qty": 1,
    "item2": null,
    "item2Qty": null,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Iron Ingot",
    "output": "Iron Ingot",
    "outputQtyPerMin": 1,
    "item1": "Desc_OreIron_C",
    "item1Qty": 1,
    "item2": null,
    "item2Qty": null,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Alternate: Nitro Rocket Fuel",
    "output": "Rocket Fuel",
    "outputQtyPerMin": 6000,
    "item1": "Fuel",
    "item1Qty": 4000,
    "item2": "Desc_NitrogenGas_C",
    "item2Qty": 3000,
    "item3": "Desc_Sulfur_C",
    "item3Qty": 4,
    "item4": "Desc_Coal_C",
    "item4Qty": 2
  },
  {
    "recipe": "Rocket Fuel",
    "output": "Rocket Fuel",
    "outputQtyPerMin": 10000,
    "item1": "Turbofuel",
    "item1Qty": 6000,
    "item2": "Nitric Acid",
    "item2Qty": 1000,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Packaged Rocket Fuel",
    "output": "Packaged Rocket Fuel",
    "outputQtyPerMin": 1,
    "item1": "Rocket Fuel",
    "item1Qty": 2000,
    "item2": "Empty Fluid Tank",
    "item2Qty": 1,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Unpackage Rocket Fuel",
    "output": "Rocket Fuel",
    "outputQtyPerMin": 2000,
    "item1": "Packaged Rocket Fuel",
    "item1Qty": 1,
    "item2": null,
    "item2Qty": null,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Ionized Fuel",
    "output": "Ionized Fuel",
    "outputQtyPerMin": 16000,
    "item1": "Rocket Fuel",
    "item1Qty": 16000,
    "item2": "Desc_CrystalShard_C",
    "item2Qty": 1,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Packaged Ionized Fuel",
    "output": "Packaged Ionized Fuel",
    "outputQtyPerMin": 2,
    "item1": "Ionized Fuel",
    "item1Qty": 4000,
    "item2": "Empty Fluid Tank",
    "item2Qty": 2,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Unpackage Ionized Fuel",
    "output": "Ionized Fuel",
    "outputQtyPerMin": 4000,
    "item1": "Packaged Ionized Fuel",
    "item1Qty": 2,
    "item2": null,
    "item2Qty": null,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "SAM Fluctuator",
    "output": "SAM Fluctuator",
    "outputQtyPerMin": 1,
    "item1": "Reanimated SAM",
    "item1Qty": 6,
    "item2": "Wire",
    "item2Qty": 5,
    "item3": "Steel Pipe",
    "item3Qty": 3,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Ficsite Trigon",
    "output": "Ficsite Trigon",
    "outputQtyPerMin": 3,
    "item1": "Ficsite Ingot",
    "item1Qty": 1,
    "item2": null,
    "item2Qty": null,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Reanimated SAM",
    "output": "Reanimated SAM",
    "outputQtyPerMin": 1,
    "item1": "Desc_SAM_C",
    "item1Qty": 4,
    "item2": null,
    "item2Qty": null,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Biochemical Sculptor",
    "output": "Biochemical Sculptor",
    "outputQtyPerMin": 4,
    "item1": "Assembly Director System",
    "item1Qty": 1,
    "item2": "Ficsite Trigon",
    "item2Qty": 80,
    "item3": "Desc_Water_C",
    "item3Qty": 20000,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Turbofuel",
    "output": "Turbofuel",
    "outputQtyPerMin": 5000,
    "item1": "Fuel",
    "item1Qty": 6000,
    "item2": "Compacted Coal",
    "item2Qty": 4,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Packaged Turbofuel",
    "output": "Packaged Turbofuel",
    "outputQtyPerMin": 2,
    "item1": "Turbofuel",
    "item1Qty": 2000,
    "item2": "Empty Canister",
    "item2Qty": 2,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Unpackage Turbofuel",
    "output": "Turbofuel",
    "outputQtyPerMin": 2000,
    "item1": "Packaged Turbofuel",
    "item1Qty": 2,
    "item2": null,
    "item2Qty": null,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Alternate: Charcoal",
    "output": "Desc_Coal_C",
    "outputQtyPerMin": 10,
    "item1": "Desc_Wood_C",
    "item1Qty": 1,
    "item2": null,
    "item2Qty": null,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Alternate: Biocoal",
    "output": "Desc_Coal_C",
    "outputQtyPerMin": 6,
    "item1": "Desc_GenericBiomass_C",
    "item1Qty": 5,
    "item2": null,
    "item2Qty": null,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Alternate: Compacted Coal",
    "output": "Compacted Coal",
    "outputQtyPerMin": 5,
    "item1": "Desc_Coal_C",
    "item1Qty": 5,
    "item2": "Desc_Sulfur_C",
    "item2Qty": 5,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Circuit Board",
    "output": "Circuit Board",
    "outputQtyPerMin": 1,
    "item1": "Copper Sheet",
    "item1Qty": 2,
    "item2": "Plastic",
    "item2Qty": 4,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Fuel",
    "output": "Fuel",
    "outputQtyPerMin": 4000,
    "item1": "Desc_LiquidOil_C",
    "item1Qty": 6000,
    "item2": null,
    "item2Qty": null,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Petroleum Coke",
    "output": "Petroleum Coke",
    "outputQtyPerMin": 12,
    "item1": "Heavy Oil Residue",
    "item1Qty": 4000,
    "item2": null,
    "item2Qty": null,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Plastic",
    "output": "Plastic",
    "outputQtyPerMin": 2,
    "item1": "Desc_LiquidOil_C",
    "item1Qty": 3000,
    "item2": null,
    "item2Qty": null,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Rubber",
    "output": "Rubber",
    "outputQtyPerMin": 2,
    "item1": "Desc_LiquidOil_C",
    "item1Qty": 3000,
    "item2": null,
    "item2Qty": null,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Residual Fuel",
    "output": "Fuel",
    "outputQtyPerMin": 4000,
    "item1": "Heavy Oil Residue",
    "item1Qty": 6000,
    "item2": null,
    "item2Qty": null,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Residual Plastic",
    "output": "Plastic",
    "outputQtyPerMin": 2,
    "item1": "Polymer Resin",
    "item1Qty": 6,
    "item2": "Desc_Water_C",
    "item2Qty": 2000,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Residual Rubber",
    "output": "Rubber",
    "outputQtyPerMin": 2,
    "item1": "Polymer Resin",
    "item1Qty": 4,
    "item2": "Desc_Water_C",
    "item2Qty": 4000,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Alternate: Wet Concrete",
    "output": "Concrete",
    "outputQtyPerMin": 4,
    "item1": "Desc_Stone_C",
    "item1Qty": 6,
    "item2": "Desc_Water_C",
    "item2Qty": 5000,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Alternate: Turbo Heavy Fuel",
    "output": "Turbofuel",
    "outputQtyPerMin": 4000,
    "item1": "Heavy Oil Residue",
    "item1Qty": 5000,
    "item2": "Compacted Coal",
    "item2Qty": 4,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Alternate: Steel Rod",
    "output": "Iron Rod",
    "outputQtyPerMin": 4,
    "item1": "Steel Ingot",
    "item1Qty": 1,
    "item2": null,
    "item2Qty": null,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Steel Beam",
    "output": "Steel Beam",
    "outputQtyPerMin": 1,
    "item1": "Steel Ingot",
    "item1Qty": 4,
    "item2": null,
    "item2Qty": null,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Steel Pipe",
    "output": "Steel Pipe",
    "outputQtyPerMin": 2,
    "item1": "Steel Ingot",
    "item1Qty": 3,
    "item2": null,
    "item2Qty": null,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Steel Ingot",
    "output": "Steel Ingot",
    "outputQtyPerMin": 3,
    "item1": "Desc_OreIron_C",
    "item1Qty": 3,
    "item2": "Desc_Coal_C",
    "item2Qty": 3,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Versatile Framework",
    "output": "Versatile Framework",
    "outputQtyPerMin": 2,
    "item1": "Modular Frame",
    "item1Qty": 1,
    "item2": "Steel Beam",
    "item2Qty": 12,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Alternate: Steel Canister",
    "output": "Empty Canister",
    "outputQtyPerMin": 4,
    "item1": "Steel Ingot",
    "item1Qty": 4,
    "item2": null,
    "item2Qty": null,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Empty Canister",
    "output": "Empty Canister",
    "outputQtyPerMin": 4,
    "item1": "Plastic",
    "item1Qty": 2,
    "item2": null,
    "item2Qty": null,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Packaged Fuel",
    "output": "Packaged Fuel",
    "outputQtyPerMin": 2,
    "item1": "Fuel",
    "item1Qty": 2000,
    "item2": "Empty Canister",
    "item2Qty": 2,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Liquid Biofuel",
    "output": "Desc_LiquidBiofuel_C",
    "outputQtyPerMin": 4000,
    "item1": "Desc_Biofuel_C",
    "item1Qty": 6,
    "item2": "Desc_Water_C",
    "item2Qty": 3000,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Packaged Liquid Biofuel",
    "output": "Desc_PackagedBiofuel_C",
    "outputQtyPerMin": 2,
    "item1": "Desc_LiquidBiofuel_C",
    "item1Qty": 2000,
    "item2": "Empty Canister",
    "item2Qty": 2,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Packaged Oil",
    "output": "Packaged Oil",
    "outputQtyPerMin": 2,
    "item1": "Desc_LiquidOil_C",
    "item1Qty": 2000,
    "item2": "Empty Canister",
    "item2Qty": 2,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Packaged Heavy Oil Residue",
    "output": "Packaged Heavy Oil Residue",
    "outputQtyPerMin": 2,
    "item1": "Heavy Oil Residue",
    "item1Qty": 2000,
    "item2": "Empty Canister",
    "item2Qty": 2,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Packaged Water",
    "output": "Packaged Water",
    "outputQtyPerMin": 2,
    "item1": "Desc_Water_C",
    "item1Qty": 2000,
    "item2": "Empty Canister",
    "item2Qty": 2,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Unpackage Liquid Biofuel",
    "output": "Desc_LiquidBiofuel_C",
    "outputQtyPerMin": 2000,
    "item1": "Desc_PackagedBiofuel_C",
    "item1Qty": 2,
    "item2": null,
    "item2Qty": null,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Unpackage Fuel",
    "output": "Fuel",
    "outputQtyPerMin": 2000,
    "item1": "Packaged Fuel",
    "item1Qty": 2,
    "item2": null,
    "item2Qty": null,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Unpackage Oil",
    "output": "Desc_LiquidOil_C",
    "outputQtyPerMin": 2000,
    "item1": "Packaged Oil",
    "item1Qty": 2,
    "item2": null,
    "item2Qty": null,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Unpackage Heavy Oil Residue",
    "output": "Heavy Oil Residue",
    "outputQtyPerMin": 2000,
    "item1": "Packaged Heavy Oil Residue",
    "item1Qty": 2,
    "item2": null,
    "item2Qty": null,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Unpackage Water",
    "output": "Desc_Water_C",
    "outputQtyPerMin": 2000,
    "item1": "Packaged Water",
    "item1Qty": 2,
    "item2": null,
    "item2Qty": null,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Alternate: Steamed Copper Sheet",
    "output": "Copper Sheet",
    "outputQtyPerMin": 3,
    "item1": "Copper Ingot",
    "item1Qty": 3,
    "item2": "Desc_Water_C",
    "item2Qty": 3000,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Alternate: Rubber Concrete",
    "output": "Concrete",
    "outputQtyPerMin": 9,
    "item1": "Desc_Stone_C",
    "item1Qty": 10,
    "item2": "Rubber",
    "item2Qty": 2,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Alternate: Recycled Rubber",
    "output": "Rubber",
    "outputQtyPerMin": 12,
    "item1": "Plastic",
    "item1Qty": 6,
    "item2": "Fuel",
    "item2Qty": 6000,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Alternate: Pure Quartz Crystal",
    "output": "Quartz Crystal",
    "outputQtyPerMin": 7,
    "item1": "Desc_RawQuartz_C",
    "item1Qty": 9,
    "item2": "Desc_Water_C",
    "item2Qty": 5000,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Quartz Crystal",
    "output": "Quartz Crystal",
    "outputQtyPerMin": 3,
    "item1": "Desc_RawQuartz_C",
    "item1Qty": 5,
    "item2": null,
    "item2Qty": null,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Alternate: Pure Iron Ingot",
    "output": "Iron Ingot",
    "outputQtyPerMin": 13,
    "item1": "Desc_OreIron_C",
    "item1Qty": 7,
    "item2": "Desc_Water_C",
    "item2Qty": 4000,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Alternate: Pure Copper Ingot",
    "output": "Copper Ingot",
    "outputQtyPerMin": 15,
    "item1": "Desc_OreCopper_C",
    "item1Qty": 6,
    "item2": "Desc_Water_C",
    "item2Qty": 4000,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Alternate: Pure Caterium Ingot",
    "output": "Caterium Ingot",
    "outputQtyPerMin": 1,
    "item1": "Desc_OreGold_C",
    "item1Qty": 2,
    "item2": "Desc_Water_C",
    "item2Qty": 2000,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Alternate: Pure Aluminum Ingot",
    "output": "Aluminum Ingot",
    "outputQtyPerMin": 1,
    "item1": "Aluminum Scrap",
    "item1Qty": 2,
    "item2": null,
    "item2Qty": null,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Aluminum Casing",
    "output": "Aluminum Casing",
    "outputQtyPerMin": 2,
    "item1": "Aluminum Ingot",
    "item1Qty": 3,
    "item2": null,
    "item2Qty": null,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Alclad Aluminum Sheet",
    "output": "Alclad Aluminum Sheet",
    "outputQtyPerMin": 3,
    "item1": "Aluminum Ingot",
    "item1Qty": 3,
    "item2": "Copper Ingot",
    "item2Qty": 1,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Alumina Solution",
    "output": "Alumina Solution",
    "outputQtyPerMin": 12000,
    "item1": "Desc_OreBauxite_C",
    "item1Qty": 12,
    "item2": "Desc_Water_C",
    "item2Qty": 18000,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Aluminum Scrap",
    "output": "Aluminum Scrap",
    "outputQtyPerMin": 6,
    "item1": "Alumina Solution",
    "item1Qty": 4000,
    "item2": "Desc_Coal_C",
    "item2Qty": 2,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Packaged Alumina Solution",
    "output": "Desc_PackagedAlumina_C",
    "outputQtyPerMin": 2,
    "item1": "Alumina Solution",
    "item1Qty": 2000,
    "item2": "Empty Canister",
    "item2Qty": 2,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Aluminum Ingot",
    "output": "Aluminum Ingot",
    "outputQtyPerMin": 4,
    "item1": "Aluminum Scrap",
    "item1Qty": 6,
    "item2": "Silica",
    "item2Qty": 5,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Silica",
    "output": "Silica",
    "outputQtyPerMin": 5,
    "item1": "Desc_RawQuartz_C",
    "item1Qty": 3,
    "item2": null,
    "item2Qty": null,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Crystal Oscillator",
    "output": "Crystal Oscillator",
    "outputQtyPerMin": 2,
    "item1": "Quartz Crystal",
    "item1Qty": 36,
    "item2": "Cable",
    "item2Qty": 28,
    "item3": "Reinforced Iron Plate",
    "item3Qty": 5,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Unpackage Alumina Solution",
    "output": "Alumina Solution",
    "outputQtyPerMin": 2000,
    "item1": "Desc_PackagedAlumina_C",
    "item1Qty": 2,
    "item2": null,
    "item2Qty": null,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Alternate: Polymer Resin",
    "output": "Polymer Resin",
    "outputQtyPerMin": 13,
    "item1": "Desc_LiquidOil_C",
    "item1Qty": 6000,
    "item2": null,
    "item2Qty": null,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Alternate: Plastic Smart Plating",
    "output": "Smart Plating",
    "outputQtyPerMin": 2,
    "item1": "Reinforced Iron Plate",
    "item1Qty": 1,
    "item2": "Rotor",
    "item2Qty": 1,
    "item3": "Plastic",
    "item3Qty": 3,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Alternate: Automated Speed Wiring",
    "output": "Automated Wiring",
    "outputQtyPerMin": 4,
    "item1": "Stator",
    "item1Qty": 2,
    "item2": "Wire",
    "item2Qty": 40,
    "item3": "High-Speed Connector",
    "item3Qty": 1,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Encased Industrial Beam",
    "output": "Encased Industrial Beam",
    "outputQtyPerMin": 1,
    "item1": "Steel Beam",
    "item1Qty": 3,
    "item2": "Concrete",
    "item2Qty": 6,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Motor",
    "output": "Motor",
    "outputQtyPerMin": 1,
    "item1": "Rotor",
    "item1Qty": 2,
    "item2": "Stator",
    "item2Qty": 2,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Stator",
    "output": "Stator",
    "outputQtyPerMin": 1,
    "item1": "Steel Pipe",
    "item1Qty": 3,
    "item2": "Wire",
    "item2Qty": 8,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Automated Wiring",
    "output": "Automated Wiring",
    "outputQtyPerMin": 1,
    "item1": "Stator",
    "item1Qty": 1,
    "item2": "Cable",
    "item2Qty": 20,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "AI Limiter",
    "output": "AI Limiter",
    "outputQtyPerMin": 1,
    "item1": "Copper Sheet",
    "item1Qty": 5,
    "item2": "Quickwire",
    "item2Qty": 20,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Alternate: Heavy Oil Residue",
    "output": "Heavy Oil Residue",
    "outputQtyPerMin": 4000,
    "item1": "Desc_LiquidOil_C",
    "item1Qty": 3000,
    "item2": null,
    "item2Qty": null,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Alternate: Heavy Flexible Frame",
    "output": "Heavy Modular Frame",
    "outputQtyPerMin": 1,
    "item1": "Modular Frame",
    "item1Qty": 5,
    "item2": "Encased Industrial Beam",
    "item2Qty": 3,
    "item3": "Rubber",
    "item3Qty": 20,
    "item4": "Screws",
    "item4Qty": 104
  },
  {
    "recipe": "Computer",
    "output": "Computer",
    "outputQtyPerMin": 1,
    "item1": "Circuit Board",
    "item1Qty": 4,
    "item2": "Cable",
    "item2Qty": 8,
    "item3": "Plastic",
    "item3Qty": 16,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Heavy Modular Frame",
    "output": "Heavy Modular Frame",
    "outputQtyPerMin": 1,
    "item1": "Modular Frame",
    "item1Qty": 5,
    "item2": "Steel Pipe",
    "item2Qty": 20,
    "item3": "Encased Industrial Beam",
    "item3Qty": 5,
    "item4": "Screws",
    "item4Qty": 120
  },
  {
    "recipe": "Modular Engine",
    "output": "Modular Engine",
    "outputQtyPerMin": 1,
    "item1": "Motor",
    "item1Qty": 2,
    "item2": "Rubber",
    "item2Qty": 15,
    "item3": "Smart Plating",
    "item3Qty": 2,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Adaptive Control Unit",
    "output": "Adaptive Control Unit",
    "outputQtyPerMin": 1,
    "item1": "Automated Wiring",
    "item1Qty": 5,
    "item2": "Circuit Board",
    "item2Qty": 5,
    "item3": "Heavy Modular Frame",
    "item3Qty": 1,
    "item4": "Computer",
    "item4Qty": 2
  },
  {
    "recipe": "Alternate: Fused Wire",
    "output": "Wire",
    "outputQtyPerMin": 30,
    "item1": "Copper Ingot",
    "item1Qty": 4,
    "item2": "Caterium Ingot",
    "item2Qty": 1,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Alternate: Flexible Framework",
    "output": "Versatile Framework",
    "outputQtyPerMin": 2,
    "item1": "Modular Frame",
    "item1Qty": 1,
    "item2": "Steel Beam",
    "item2Qty": 6,
    "item3": "Rubber",
    "item3Qty": 8,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Alternate: Electrode Circuit Board",
    "output": "Circuit Board",
    "outputQtyPerMin": 1,
    "item1": "Rubber",
    "item1Qty": 4,
    "item2": "Petroleum Coke",
    "item2Qty": 8,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Alternate: Electrode Aluminum Scrap",
    "output": "Aluminum Scrap",
    "outputQtyPerMin": 20,
    "item1": "Alumina Solution",
    "item1Qty": 12000,
    "item2": "Petroleum Coke",
    "item2Qty": 4,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Alternate: Diluted Packaged Fuel",
    "output": "Packaged Fuel",
    "outputQtyPerMin": 2,
    "item1": "Heavy Oil Residue",
    "item1Qty": 1000,
    "item2": "Packaged Water",
    "item2Qty": 2,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Alternate: Copper Rotor",
    "output": "Rotor",
    "outputQtyPerMin": 3,
    "item1": "Copper Sheet",
    "item1Qty": 6,
    "item2": "Screws",
    "item2Qty": 52,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Modular Frame",
    "output": "Modular Frame",
    "outputQtyPerMin": 2,
    "item1": "Reinforced Iron Plate",
    "item1Qty": 3,
    "item2": "Iron Rod",
    "item2Qty": 12,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Rotor",
    "output": "Rotor",
    "outputQtyPerMin": 1,
    "item1": "Iron Rod",
    "item1Qty": 5,
    "item2": "Screws",
    "item2Qty": 25,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Copper Sheet",
    "output": "Copper Sheet",
    "outputQtyPerMin": 1,
    "item1": "Copper Ingot",
    "item1Qty": 2,
    "item2": null,
    "item2Qty": null,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Smart Plating",
    "output": "Smart Plating",
    "outputQtyPerMin": 1,
    "item1": "Reinforced Iron Plate",
    "item1Qty": 1,
    "item2": "Rotor",
    "item2Qty": 1,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Alternate: Copper Alloy Ingot",
    "output": "Copper Ingot",
    "outputQtyPerMin": 10,
    "item1": "Desc_OreCopper_C",
    "item1Qty": 5,
    "item2": "Desc_OreIron_C",
    "item2Qty": 5,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Alternate: Coke Steel Ingot",
    "output": "Steel Ingot",
    "outputQtyPerMin": 20,
    "item1": "Desc_OreIron_C",
    "item1Qty": 15,
    "item2": "Petroleum Coke",
    "item2Qty": 15,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Alternate: Coated Iron Plate",
    "output": "Iron Plate",
    "outputQtyPerMin": 10,
    "item1": "Iron Ingot",
    "item1Qty": 5,
    "item2": "Plastic",
    "item2Qty": 1,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Alternate: Coated Iron Canister",
    "output": "Empty Canister",
    "outputQtyPerMin": 4,
    "item1": "Iron Plate",
    "item1Qty": 2,
    "item2": "Copper Sheet",
    "item2Qty": 1,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Alternate: Coated Cable",
    "output": "Cable",
    "outputQtyPerMin": 9,
    "item1": "Wire",
    "item1Qty": 5,
    "item2": "Heavy Oil Residue",
    "item2Qty": 2000,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Alternate: Bolted Frame",
    "output": "Modular Frame",
    "outputQtyPerMin": 2,
    "item1": "Reinforced Iron Plate",
    "item1Qty": 3,
    "item2": "Screws",
    "item2Qty": 56,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Alternate: Adhered Iron Plate",
    "output": "Reinforced Iron Plate",
    "outputQtyPerMin": 1,
    "item1": "Iron Plate",
    "item1Qty": 3,
    "item2": "Rubber",
    "item2Qty": 1,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Alternate: Turbo Pressure Motor",
    "output": "Turbo Motor",
    "outputQtyPerMin": 2,
    "item1": "Motor",
    "item1Qty": 4,
    "item2": "Pressure Conversion Cube",
    "item2Qty": 1,
    "item3": "Desc_PackagedNitrogenGas_C",
    "item3Qty": 24,
    "item4": "Stator",
    "item4Qty": 8
  },
  {
    "recipe": "Encased Plutonium Cell",
    "output": "Encased Plutonium Cell",
    "outputQtyPerMin": 1,
    "item1": "Plutonium Pellet",
    "item1Qty": 2,
    "item2": "Concrete",
    "item2Qty": 4,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Pressure Conversion Cube",
    "output": "Pressure Conversion Cube",
    "outputQtyPerMin": 1,
    "item1": "Fused Modular Frame",
    "item1Qty": 1,
    "item2": "Radio Control Unit",
    "item2Qty": 2,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Nitric Acid",
    "output": "Nitric Acid",
    "outputQtyPerMin": 3000,
    "item1": "Desc_NitrogenGas_C",
    "item1Qty": 12000,
    "item2": "Desc_Water_C",
    "item2Qty": 3000,
    "item3": "Iron Plate",
    "item3Qty": 1,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Non-Fissile Uranium",
    "output": "Non-Fissile Uranium",
    "outputQtyPerMin": 20,
    "item1": "Uranium Waste",
    "item1Qty": 15,
    "item2": "Silica",
    "item2Qty": 10,
    "item3": "Nitric Acid",
    "item3Qty": 6000,
    "item4": "Sulfuric Acid",
    "item4Qty": 6000
  },
  {
    "recipe": "Copper Powder",
    "output": "Copper Powder",
    "outputQtyPerMin": 5,
    "item1": "Copper Ingot",
    "item1Qty": 30,
    "item2": null,
    "item2Qty": null,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Plutonium Fuel Rod",
    "output": "Desc_PlutoniumFuelRod_C",
    "outputQtyPerMin": 1,
    "item1": "Encased Plutonium Cell",
    "item1Qty": 30,
    "item2": "Steel Beam",
    "item2Qty": 18,
    "item3": "Electromagnetic Control Rod",
    "item3Qty": 6,
    "item4": "Heat Sink",
    "item4Qty": 10
  },
  {
    "recipe": "Packaged Nitric Acid",
    "output": "Desc_PackagedNitricAcid_C",
    "outputQtyPerMin": 1,
    "item1": "Nitric Acid",
    "item1Qty": 1000,
    "item2": "Empty Fluid Tank",
    "item2Qty": 1,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Unpackage Nitric Acid",
    "output": "Nitric Acid",
    "outputQtyPerMin": 1000,
    "item1": "Desc_PackagedNitricAcid_C",
    "item1Qty": 1,
    "item2": null,
    "item2Qty": null,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Alternate: Turbo Blend Fuel",
    "output": "Turbofuel",
    "outputQtyPerMin": 6000,
    "item1": "Fuel",
    "item1Qty": 2000,
    "item2": "Heavy Oil Residue",
    "item2Qty": 4000,
    "item3": "Desc_Sulfur_C",
    "item3Qty": 3,
    "item4": "Petroleum Coke",
    "item4Qty": 3
  },
  {
    "recipe": "Encased Uranium Cell",
    "output": "Encased Uranium Cell",
    "outputQtyPerMin": 5,
    "item1": "Desc_OreUranium_C",
    "item1Qty": 10,
    "item2": "Concrete",
    "item2Qty": 3,
    "item3": "Sulfuric Acid",
    "item3Qty": 8000,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Cooling System",
    "output": "Cooling System",
    "outputQtyPerMin": 1,
    "item1": "Heat Sink",
    "item1Qty": 2,
    "item2": "Rubber",
    "item2Qty": 2,
    "item3": "Desc_Water_C",
    "item3Qty": 5000,
    "item4": "Desc_NitrogenGas_C",
    "item4Qty": 25000
  },
  {
    "recipe": "Battery",
    "output": "Battery",
    "outputQtyPerMin": 1,
    "item1": "Sulfuric Acid",
    "item1Qty": 2500,
    "item2": "Alumina Solution",
    "item2Qty": 2000,
    "item3": "Aluminum Casing",
    "item3Qty": 1,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Supercomputer",
    "output": "Supercomputer",
    "outputQtyPerMin": 1,
    "item1": "Computer",
    "item1Qty": 4,
    "item2": "AI Limiter",
    "item2Qty": 2,
    "item3": "High-Speed Connector",
    "item3Qty": 3,
    "item4": "Plastic",
    "item4Qty": 28
  },
  {
    "recipe": "Radio Control Unit",
    "output": "Radio Control Unit",
    "outputQtyPerMin": 2,
    "item1": "Aluminum Casing",
    "item1Qty": 32,
    "item2": "Crystal Oscillator",
    "item2Qty": 1,
    "item3": "Computer",
    "item3Qty": 2,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Sulfuric Acid",
    "output": "Sulfuric Acid",
    "outputQtyPerMin": 5000,
    "item1": "Desc_Sulfur_C",
    "item1Qty": 5,
    "item2": "Desc_Water_C",
    "item2Qty": 5000,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Packaged Sulfuric Acid",
    "output": "Desc_PackagedSulfuricAcid_C",
    "outputQtyPerMin": 2,
    "item1": "Sulfuric Acid",
    "item1Qty": 2000,
    "item2": "Empty Canister",
    "item2Qty": 2,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Assembly Director System",
    "output": "Assembly Director System",
    "outputQtyPerMin": 1,
    "item1": "Adaptive Control Unit",
    "item1Qty": 2,
    "item2": "Supercomputer",
    "item2Qty": 1,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "High-Speed Connector",
    "output": "High-Speed Connector",
    "outputQtyPerMin": 1,
    "item1": "Quickwire",
    "item1Qty": 56,
    "item2": "Cable",
    "item2Qty": 10,
    "item3": "Circuit Board",
    "item3Qty": 1,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Unpackage Sulfuric Acid",
    "output": "Sulfuric Acid",
    "outputQtyPerMin": 1000,
    "item1": "Desc_PackagedSulfuricAcid_C",
    "item1Qty": 1,
    "item2": null,
    "item2Qty": null,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Alternate: Super-State Computer",
    "output": "Supercomputer",
    "outputQtyPerMin": 1,
    "item1": "Computer",
    "item1Qty": 3,
    "item2": "Electromagnetic Control Rod",
    "item2Qty": 1,
    "item3": "Battery",
    "item3Qty": 10,
    "item4": "Wire",
    "item4Qty": 25
  },
  {
    "recipe": "Electromagnetic Control Rod",
    "output": "Electromagnetic Control Rod",
    "outputQtyPerMin": 2,
    "item1": "Stator",
    "item1Qty": 3,
    "item2": "AI Limiter",
    "item2Qty": 2,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Uranium Fuel Rod",
    "output": "Desc_NuclearFuelRod_C",
    "outputQtyPerMin": 1,
    "item1": "Encased Uranium Cell",
    "item1Qty": 50,
    "item2": "Encased Industrial Beam",
    "item2Qty": 3,
    "item3": "Electromagnetic Control Rod",
    "item3Qty": 5,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Magnetic Field Generator",
    "output": "Magnetic Field Generator",
    "outputQtyPerMin": 2,
    "item1": "Versatile Framework",
    "item1Qty": 5,
    "item2": "Electromagnetic Control Rod",
    "item2Qty": 2,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Alternate: Sloppy Alumina",
    "output": "Alumina Solution",
    "outputQtyPerMin": 12000,
    "item1": "Desc_OreBauxite_C",
    "item1Qty": 10,
    "item2": "Desc_Water_C",
    "item2Qty": 10000,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Alternate: Radio Control System",
    "output": "Radio Control Unit",
    "outputQtyPerMin": 3,
    "item1": "Crystal Oscillator",
    "item1Qty": 1,
    "item2": "Circuit Board",
    "item2Qty": 10,
    "item3": "Aluminum Casing",
    "item3Qty": 60,
    "item4": "Rubber",
    "item4Qty": 30
  },
  {
    "recipe": "Alternate: Plutonium Fuel Unit",
    "output": "Desc_PlutoniumFuelRod_C",
    "outputQtyPerMin": 1,
    "item1": "Encased Plutonium Cell",
    "item1Qty": 20,
    "item2": "Pressure Conversion Cube",
    "item2Qty": 1,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Alternate: OC Supercomputer",
    "output": "Supercomputer",
    "outputQtyPerMin": 1,
    "item1": "Radio Control Unit",
    "item1Qty": 2,
    "item2": "Cooling System",
    "item2Qty": 2,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Heat Sink",
    "output": "Heat Sink",
    "outputQtyPerMin": 1,
    "item1": "Alclad Aluminum Sheet",
    "item1Qty": 5,
    "item2": "Copper Sheet",
    "item2Qty": 3,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Fused Modular Frame",
    "output": "Fused Modular Frame",
    "outputQtyPerMin": 1,
    "item1": "Heavy Modular Frame",
    "item1Qty": 1,
    "item2": "Aluminum Casing",
    "item2Qty": 50,
    "item3": "Desc_NitrogenGas_C",
    "item3Qty": 25000,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Empty Fluid Tank",
    "output": "Empty Fluid Tank",
    "outputQtyPerMin": 1,
    "item1": "Aluminum Ingot",
    "item1Qty": 1,
    "item2": null,
    "item2Qty": null,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Packaged Nitrogen Gas",
    "output": "Desc_PackagedNitrogenGas_C",
    "outputQtyPerMin": 1,
    "item1": "Desc_NitrogenGas_C",
    "item1Qty": 4000,
    "item2": "Empty Fluid Tank",
    "item2Qty": 1,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Unpackage Nitrogen Gas",
    "output": "Desc_NitrogenGas_C",
    "outputQtyPerMin": 4000,
    "item1": "Desc_PackagedNitrogenGas_C",
    "item1Qty": 1,
    "item2": null,
    "item2Qty": null,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Alternate: Instant Scrap",
    "output": "Aluminum Scrap",
    "outputQtyPerMin": 30,
    "item1": "Desc_OreBauxite_C",
    "item1Qty": 15,
    "item2": "Desc_Coal_C",
    "item2Qty": 10,
    "item3": "Sulfuric Acid",
    "item3Qty": 5000,
    "item4": "Desc_Water_C",
    "item4Qty": 6000
  },
  {
    "recipe": "Alternate: Heat-Fused Frame",
    "output": "Fused Modular Frame",
    "outputQtyPerMin": 1,
    "item1": "Heavy Modular Frame",
    "item1Qty": 1,
    "item2": "Aluminum Ingot",
    "item2Qty": 50,
    "item3": "Nitric Acid",
    "item3Qty": 8000,
    "item4": "Fuel",
    "item4Qty": 10000
  },
  {
    "recipe": "Alternate: Fertile Uranium",
    "output": "Non-Fissile Uranium",
    "outputQtyPerMin": 20,
    "item1": "Desc_OreUranium_C",
    "item1Qty": 5,
    "item2": "Uranium Waste",
    "item2Qty": 5,
    "item3": "Nitric Acid",
    "item3Qty": 3000,
    "item4": "Sulfuric Acid",
    "item4Qty": 5000
  },
  {
    "recipe": "Alternate: Electric Motor",
    "output": "Motor",
    "outputQtyPerMin": 2,
    "item1": "Electromagnetic Control Rod",
    "item1Qty": 1,
    "item2": "Rotor",
    "item2Qty": 2,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Alternate: Diluted Fuel",
    "output": "Fuel",
    "outputQtyPerMin": 10000,
    "item1": "Heavy Oil Residue",
    "item1Qty": 5000,
    "item2": "Desc_Water_C",
    "item2Qty": 10000,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Alternate: Cooling Device",
    "output": "Cooling System",
    "outputQtyPerMin": 2,
    "item1": "Heat Sink",
    "item1Qty": 4,
    "item2": "Motor",
    "item2Qty": 1,
    "item3": "Desc_NitrogenGas_C",
    "item3Qty": 24000,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Alternate: Classic Battery",
    "output": "Battery",
    "outputQtyPerMin": 4,
    "item1": "Desc_Sulfur_C",
    "item1Qty": 6,
    "item2": "Alclad Aluminum Sheet",
    "item2Qty": 7,
    "item3": "Plastic",
    "item3Qty": 8,
    "item4": "Wire",
    "item4Qty": 12
  },
  {
    "recipe": "Alternate: Automated Miner",
    "output": "",
    "outputQtyPerMin": 1,
    "item1": "Steel Pipe",
    "item1Qty": 4,
    "item2": "Iron Plate",
    "item2Qty": 4,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Alternate: Alclad Casing",
    "output": "Aluminum Casing",
    "outputQtyPerMin": 15,
    "item1": "Aluminum Ingot",
    "item1Qty": 20,
    "item2": "Copper Ingot",
    "item2Qty": 10,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Alternate: Molded Steel Pipe",
    "output": "Steel Pipe",
    "outputQtyPerMin": 5,
    "item1": "Steel Ingot",
    "item1Qty": 5,
    "item2": "Concrete",
    "item2Qty": 3,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Alternate: Iron Pipe",
    "output": "Steel Pipe",
    "outputQtyPerMin": 5,
    "item1": "Iron Ingot",
    "item1Qty": 20,
    "item2": null,
    "item2Qty": null,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Alternate: Steel Cast Plate",
    "output": "Iron Plate",
    "outputQtyPerMin": 3,
    "item1": "Iron Ingot",
    "item1Qty": 1,
    "item2": "Steel Ingot",
    "item2Qty": 1,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Alternate: Molded Beam",
    "output": "Steel Beam",
    "outputQtyPerMin": 9,
    "item1": "Steel Ingot",
    "item1Qty": 24,
    "item2": "Concrete",
    "item2Qty": 16,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Alternate: Aluminum Beam",
    "output": "Steel Beam",
    "outputQtyPerMin": 3,
    "item1": "Aluminum Ingot",
    "item1Qty": 3,
    "item2": null,
    "item2Qty": null,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Alternate: Aluminum Rod",
    "output": "Iron Rod",
    "outputQtyPerMin": 7,
    "item1": "Aluminum Ingot",
    "item1Qty": 1,
    "item2": null,
    "item2Qty": null,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Alternate: Plastic AI Limiter",
    "output": "AI Limiter",
    "outputQtyPerMin": 2,
    "item1": "Quickwire",
    "item1Qty": 30,
    "item2": "Plastic",
    "item2Qty": 7,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Alternate: Distilled Silica",
    "output": "Silica",
    "outputQtyPerMin": 27,
    "item1": "Dissolved Silica",
    "item1Qty": 12000,
    "item2": "Desc_Stone_C",
    "item2Qty": 5,
    "item3": "Desc_Water_C",
    "item3Qty": 10000,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Alternate: Quartz Purification",
    "output": "Quartz Crystal",
    "outputQtyPerMin": 15,
    "item1": "Desc_RawQuartz_C",
    "item1Qty": 24,
    "item2": "Nitric Acid",
    "item2Qty": 2000,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Alternate: Fused Quartz Crystal",
    "output": "Quartz Crystal",
    "outputQtyPerMin": 18,
    "item1": "Desc_RawQuartz_C",
    "item1Qty": 25,
    "item2": "Desc_Coal_C",
    "item2Qty": 12,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Alternate: Leached Iron Ingot",
    "output": "Iron Ingot",
    "outputQtyPerMin": 10,
    "item1": "Desc_OreIron_C",
    "item1Qty": 5,
    "item2": "Sulfuric Acid",
    "item2Qty": 1000,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Alternate: Basic Iron Ingot",
    "output": "Iron Ingot",
    "outputQtyPerMin": 10,
    "item1": "Desc_OreIron_C",
    "item1Qty": 5,
    "item2": "Desc_Stone_C",
    "item2Qty": 8,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Alternate: Tempered Copper Ingot",
    "output": "Copper Ingot",
    "outputQtyPerMin": 12,
    "item1": "Desc_OreCopper_C",
    "item1Qty": 5,
    "item2": "Petroleum Coke",
    "item2Qty": 8,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Alternate: Leached Copper Ingot",
    "output": "Copper Ingot",
    "outputQtyPerMin": 22,
    "item1": "Desc_OreCopper_C",
    "item1Qty": 9,
    "item2": "Sulfuric Acid",
    "item2Qty": 5000,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Alternate: Tempered Caterium Ingot",
    "output": "Caterium Ingot",
    "outputQtyPerMin": 3,
    "item1": "Desc_OreGold_C",
    "item1Qty": 6,
    "item2": "Petroleum Coke",
    "item2Qty": 2,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Alternate: Leached Caterium Ingot",
    "output": "Caterium Ingot",
    "outputQtyPerMin": 6,
    "item1": "Desc_OreGold_C",
    "item1Qty": 9,
    "item2": "Sulfuric Acid",
    "item2Qty": 5000,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Alternate: Caterium Wire",
    "output": "Wire",
    "outputQtyPerMin": 8,
    "item1": "Caterium Ingot",
    "item1Qty": 1,
    "item2": null,
    "item2Qty": null,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Alternate: Iron Wire",
    "output": "Wire",
    "outputQtyPerMin": 9,
    "item1": "Iron Ingot",
    "item1Qty": 5,
    "item2": null,
    "item2Qty": null,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Alternate: Infused Uranium Cell",
    "output": "Encased Uranium Cell",
    "outputQtyPerMin": 4,
    "item1": "Desc_OreUranium_C",
    "item1Qty": 5,
    "item2": "Silica",
    "item2Qty": 3,
    "item3": "Desc_Sulfur_C",
    "item3Qty": 5,
    "item4": "Quickwire",
    "item4Qty": 15
  },
  {
    "recipe": "Caterium Ingot",
    "output": "Caterium Ingot",
    "outputQtyPerMin": 1,
    "item1": "Desc_OreGold_C",
    "item1Qty": 3,
    "item2": null,
    "item2Qty": null,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Alternate: Turbo Electric Motor",
    "output": "Turbo Motor",
    "outputQtyPerMin": 3,
    "item1": "Motor",
    "item1Qty": 7,
    "item2": "Radio Control Unit",
    "item2Qty": 9,
    "item3": "Electromagnetic Control Rod",
    "item3Qty": 5,
    "item4": "Rotor",
    "item4Qty": 7
  },
  {
    "recipe": "Turbo Motor",
    "output": "Turbo Motor",
    "outputQtyPerMin": 1,
    "item1": "Cooling System",
    "item1Qty": 4,
    "item2": "Radio Control Unit",
    "item2Qty": 2,
    "item3": "Motor",
    "item3Qty": 4,
    "item4": "Rubber",
    "item4Qty": 24
  },
  {
    "recipe": "Thermal Propulsion Rocket",
    "output": "Thermal Propulsion Rocket",
    "outputQtyPerMin": 2,
    "item1": "Modular Engine",
    "item1Qty": 5,
    "item2": "Turbo Motor",
    "item2Qty": 2,
    "item3": "Cooling System",
    "item3Qty": 6,
    "item4": "Fused Modular Frame",
    "item4Qty": 2
  },
  {
    "recipe": "Alternate: Quickwire Stator",
    "output": "Stator",
    "outputQtyPerMin": 2,
    "item1": "Steel Pipe",
    "item1Qty": 4,
    "item2": "Quickwire",
    "item2Qty": 15,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Alternate: Cheap Silica",
    "output": "Silica",
    "outputQtyPerMin": 7,
    "item1": "Desc_RawQuartz_C",
    "item1Qty": 3,
    "item2": "Desc_Stone_C",
    "item2Qty": 5,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Alternate: Steel Screws",
    "output": "Screws",
    "outputQtyPerMin": 52,
    "item1": "Steel Beam",
    "item1Qty": 1,
    "item2": null,
    "item2Qty": null,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Alternate: Cast Screws",
    "output": "Screws",
    "outputQtyPerMin": 20,
    "item1": "Iron Ingot",
    "item1Qty": 5,
    "item2": null,
    "item2Qty": null,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Alternate: Steel Rotor",
    "output": "Rotor",
    "outputQtyPerMin": 1,
    "item1": "Steel Pipe",
    "item1Qty": 2,
    "item2": "Wire",
    "item2Qty": 6,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Alternate: Encased Industrial Pipe",
    "output": "Encased Industrial Beam",
    "outputQtyPerMin": 1,
    "item1": "Steel Pipe",
    "item1Qty": 6,
    "item2": "Concrete",
    "item2Qty": 5,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Alternate: Stitched Iron Plate",
    "output": "Reinforced Iron Plate",
    "outputQtyPerMin": 3,
    "item1": "Iron Plate",
    "item1Qty": 10,
    "item2": "Wire",
    "item2Qty": 20,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Alternate: Bolted Iron Plate",
    "output": "Reinforced Iron Plate",
    "outputQtyPerMin": 3,
    "item1": "Iron Plate",
    "item1Qty": 18,
    "item2": "Screws",
    "item2Qty": 50,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Alternate: Radio Connection Unit",
    "output": "Radio Control Unit",
    "outputQtyPerMin": 1,
    "item1": "Heat Sink",
    "item1Qty": 4,
    "item2": "High-Speed Connector",
    "item2Qty": 2,
    "item3": "Quartz Crystal",
    "item3Qty": 12,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Alternate: Fused Quickwire",
    "output": "Quickwire",
    "outputQtyPerMin": 12,
    "item1": "Caterium Ingot",
    "item1Qty": 1,
    "item2": "Copper Ingot",
    "item2Qty": 5,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Alternate: Recycled Plastic",
    "output": "Plastic",
    "outputQtyPerMin": 12,
    "item1": "Rubber",
    "item1Qty": 6,
    "item2": "Fuel",
    "item2Qty": 6000,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Alternate: Uranium Fuel Unit",
    "output": "Desc_NuclearFuelRod_C",
    "outputQtyPerMin": 3,
    "item1": "Encased Uranium Cell",
    "item1Qty": 100,
    "item2": "Electromagnetic Control Rod",
    "item2Qty": 10,
    "item3": "Crystal Oscillator",
    "item3Qty": 3,
    "item4": "Rotor",
    "item4Qty": 10
  },
  {
    "recipe": "Alternate: Rigor Motor",
    "output": "Motor",
    "outputQtyPerMin": 6,
    "item1": "Rotor",
    "item1Qty": 3,
    "item2": "Stator",
    "item2Qty": 3,
    "item3": "Crystal Oscillator",
    "item3Qty": 1,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Alternate: Steeled Frame",
    "output": "Modular Frame",
    "outputQtyPerMin": 3,
    "item1": "Reinforced Iron Plate",
    "item1Qty": 2,
    "item2": "Steel Pipe",
    "item2Qty": 10,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Alternate: Compacted Steel Ingot",
    "output": "Steel Ingot",
    "outputQtyPerMin": 4,
    "item1": "Desc_OreIron_C",
    "item1Qty": 2,
    "item2": "Compacted Coal",
    "item2Qty": 1,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Alternate: Solid Steel Ingot",
    "output": "Steel Ingot",
    "outputQtyPerMin": 3,
    "item1": "Iron Ingot",
    "item1Qty": 2,
    "item2": "Desc_Coal_C",
    "item2Qty": 2,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Alternate: Iron Alloy Ingot",
    "output": "Iron Ingot",
    "outputQtyPerMin": 15,
    "item1": "Desc_OreIron_C",
    "item1Qty": 8,
    "item2": "Desc_OreCopper_C",
    "item2Qty": 2,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Alternate: Silicon High-Speed Connector",
    "output": "High-Speed Connector",
    "outputQtyPerMin": 2,
    "item1": "Quickwire",
    "item1Qty": 60,
    "item2": "Silica",
    "item2Qty": 25,
    "item3": "Circuit Board",
    "item3Qty": 2,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Alternate: Heavy Encased Frame",
    "output": "Heavy Modular Frame",
    "outputQtyPerMin": 3,
    "item1": "Modular Frame",
    "item1Qty": 8,
    "item2": "Encased Industrial Beam",
    "item2Qty": 10,
    "item3": "Steel Pipe",
    "item3Qty": 36,
    "item4": "Concrete",
    "item4Qty": 22
  },
  {
    "recipe": "Alternate: Heat Exchanger",
    "output": "Heat Sink",
    "outputQtyPerMin": 1,
    "item1": "Aluminum Casing",
    "item1Qty": 3,
    "item2": "Rubber",
    "item2Qty": 3,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Alternate: Fine Black Powder",
    "output": "Black Powder",
    "outputQtyPerMin": 6,
    "item1": "Desc_Sulfur_C",
    "item1Qty": 1,
    "item2": "Compacted Coal",
    "item2Qty": 2,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Alternate: Electromagnetic Connection Rod",
    "output": "Electromagnetic Control Rod",
    "outputQtyPerMin": 2,
    "item1": "Stator",
    "item1Qty": 2,
    "item2": "High-Speed Connector",
    "item2Qty": 1,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Alternate: Insulated Crystal Oscillator",
    "output": "Crystal Oscillator",
    "outputQtyPerMin": 1,
    "item1": "Quartz Crystal",
    "item1Qty": 10,
    "item2": "Rubber",
    "item2Qty": 7,
    "item3": "AI Limiter",
    "item3Qty": 1,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Alternate: Fine Concrete",
    "output": "Concrete",
    "outputQtyPerMin": 10,
    "item1": "Silica",
    "item1Qty": 3,
    "item2": "Desc_Stone_C",
    "item2Qty": 12,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Alternate: Crystal Computer",
    "output": "Computer",
    "outputQtyPerMin": 2,
    "item1": "Circuit Board",
    "item1Qty": 3,
    "item2": "Crystal Oscillator",
    "item2Qty": 1,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Alternate: Caterium Computer",
    "output": "Computer",
    "outputQtyPerMin": 1,
    "item1": "Circuit Board",
    "item1Qty": 4,
    "item2": "Quickwire",
    "item2Qty": 14,
    "item3": "Rubber",
    "item3Qty": 6,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Alternate: Caterium Circuit Board",
    "output": "Circuit Board",
    "outputQtyPerMin": 7,
    "item1": "Plastic",
    "item1Qty": 10,
    "item2": "Quickwire",
    "item2Qty": 30,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Alternate: Silicon Circuit Board",
    "output": "Circuit Board",
    "outputQtyPerMin": 5,
    "item1": "Copper Sheet",
    "item1Qty": 11,
    "item2": "Silica",
    "item2Qty": 11,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Alternate: Quickwire Cable",
    "output": "Cable",
    "outputQtyPerMin": 11,
    "item1": "Quickwire",
    "item1Qty": 3,
    "item2": "Rubber",
    "item2Qty": 2,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Alternate: Insulated Cable",
    "output": "Cable",
    "outputQtyPerMin": 20,
    "item1": "Wire",
    "item1Qty": 9,
    "item2": "Rubber",
    "item2Qty": 6,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Singularity Cell",
    "output": "Singularity Cell",
    "outputQtyPerMin": 10,
    "item1": "Nuclear Pasta",
    "item1Qty": 1,
    "item2": "Dark Matter Crystal",
    "item2Qty": 20,
    "item3": "Iron Plate",
    "item3Qty": 100,
    "item4": "Concrete",
    "item4Qty": 200
  },
  {
    "recipe": "Ballistic Warp Drive",
    "output": "Ballistic Warp Drive",
    "outputQtyPerMin": 1,
    "item1": "Thermal Propulsion Rocket",
    "item1Qty": 1,
    "item2": "Singularity Cell",
    "item2Qty": 5,
    "item3": "Superposition Oscillator",
    "item3Qty": 2,
    "item4": "Dark Matter Crystal",
    "item4Qty": 40
  },
  {
    "recipe": "Iodine-Infused Filter",
    "output": "Iodine-Infused Filter",
    "outputQtyPerMin": 1,
    "item1": "Gas Filter",
    "item1Qty": 1,
    "item2": "Quickwire",
    "item2Qty": 8,
    "item3": "Aluminum Casing",
    "item3Qty": 1,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Quickwire",
    "output": "Quickwire",
    "outputQtyPerMin": 5,
    "item1": "Caterium Ingot",
    "item1Qty": 1,
    "item2": null,
    "item2Qty": null,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Solid Biofuel",
    "output": "Desc_Biofuel_C",
    "outputQtyPerMin": 4,
    "item1": "Desc_GenericBiomass_C",
    "item1Qty": 8,
    "item2": null,
    "item2Qty": null,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Hog Protein",
    "output": "Alien Protein",
    "outputQtyPerMin": 1,
    "item1": "Desc_HogParts_C",
    "item1Qty": 1,
    "item2": null,
    "item2Qty": null,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Spitter Protein",
    "output": "Alien Protein",
    "outputQtyPerMin": 1,
    "item1": "Desc_SpitterParts_C",
    "item1Qty": 1,
    "item2": null,
    "item2Qty": null,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Biomass (Mycelia)",
    "output": "Desc_GenericBiomass_C",
    "outputQtyPerMin": 10,
    "item1": "Desc_Mycelia_C",
    "item1Qty": 1,
    "item2": null,
    "item2Qty": null,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Power Shard (1)",
    "output": "Desc_CrystalShard_C",
    "outputQtyPerMin": 1,
    "item1": "Blue Power Slug",
    "item1Qty": 1,
    "item2": null,
    "item2Qty": null,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Black Powder",
    "output": "Black Powder",
    "outputQtyPerMin": 2,
    "item1": "Desc_Coal_C",
    "item1Qty": 1,
    "item2": "Desc_Sulfur_C",
    "item2Qty": 1,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Stinger Protein",
    "output": "Alien Protein",
    "outputQtyPerMin": 1,
    "item1": "Desc_StingerParts_C",
    "item1Qty": 1,
    "item2": null,
    "item2Qty": null,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Hatcher Protein",
    "output": "Alien Protein",
    "outputQtyPerMin": 1,
    "item1": "Desc_HatcherParts_C",
    "item1Qty": 1,
    "item2": null,
    "item2Qty": null,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Alien DNA Capsule",
    "output": "Alien DNA Capsule",
    "outputQtyPerMin": 1,
    "item1": "Alien Protein",
    "item1Qty": 1,
    "item2": null,
    "item2Qty": null,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Biomass (Alien Protein)",
    "output": "Desc_GenericBiomass_C",
    "outputQtyPerMin": 100,
    "item1": "Alien Protein",
    "item1Qty": 1,
    "item2": null,
    "item2Qty": null,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Iron Rebar",
    "output": "Desc_SpikedRebar_C",
    "outputQtyPerMin": 1,
    "item1": "Iron Rod",
    "item1Qty": 1,
    "item2": null,
    "item2Qty": null,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Homing Rifle Ammo",
    "output": "Desc_CartridgeSmartProjectile_C",
    "outputQtyPerMin": 10,
    "item1": "Desc_CartridgeStandard_C",
    "item1Qty": 20,
    "item2": "High-Speed Connector",
    "item2Qty": 1,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Stun Rebar",
    "output": "Desc_Rebar_Stunshot_C",
    "outputQtyPerMin": 1,
    "item1": "Desc_SpikedRebar_C",
    "item1Qty": 1,
    "item2": "Quickwire",
    "item2Qty": 5,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Gas Filter",
    "output": "Gas Filter",
    "outputQtyPerMin": 1,
    "item1": "Desc_Fabric_C",
    "item1Qty": 2,
    "item2": "Desc_Coal_C",
    "item2Qty": 4,
    "item3": "Iron Plate",
    "item3Qty": 2,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Gas Nobelisk",
    "output": "Desc_NobeliskGas_C",
    "outputQtyPerMin": 1,
    "item1": "Desc_NobeliskExplosive_C",
    "item1Qty": 1,
    "item2": "Desc_GenericBiomass_C",
    "item2Qty": 10,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Alternate: Polyester Fabric",
    "output": "Desc_Fabric_C",
    "outputQtyPerMin": 1,
    "item1": "Polymer Resin",
    "item1Qty": 1,
    "item2": "Desc_Water_C",
    "item2Qty": 1000,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Fabric",
    "output": "Desc_Fabric_C",
    "outputQtyPerMin": 1,
    "item1": "Desc_Mycelia_C",
    "item1Qty": 1,
    "item2": "Desc_GenericBiomass_C",
    "item2Qty": 5,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Power Shard (5)",
    "output": "Desc_CrystalShard_C",
    "outputQtyPerMin": 5,
    "item1": "Purple Power Slug",
    "item1Qty": 1,
    "item2": null,
    "item2Qty": null,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Power Shard (2)",
    "output": "Desc_CrystalShard_C",
    "outputQtyPerMin": 2,
    "item1": "Yellow Power Slug",
    "item1Qty": 1,
    "item2": null,
    "item2Qty": null,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Pulse Nobelisk",
    "output": "Desc_NobeliskShockwave_C",
    "outputQtyPerMin": 5,
    "item1": "Desc_NobeliskExplosive_C",
    "item1Qty": 5,
    "item2": "Crystal Oscillator",
    "item2Qty": 1,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Shatter Rebar",
    "output": "Desc_Rebar_Spreadshot_C",
    "outputQtyPerMin": 1,
    "item1": "Desc_SpikedRebar_C",
    "item1Qty": 2,
    "item2": "Quartz Crystal",
    "item2Qty": 3,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Turbo Rifle Ammo",
    "output": "Desc_CartridgeChaos_C",
    "outputQtyPerMin": 50,
    "item1": "Desc_CartridgeStandard_C",
    "item1Qty": 25,
    "item2": "Aluminum Casing",
    "item2Qty": 3,
    "item3": "Packaged Turbofuel",
    "item3Qty": 3,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Turbo Rifle Ammo",
    "output": "Desc_CartridgeChaos_C",
    "outputQtyPerMin": 50,
    "item1": "Desc_CartridgeStandard_C",
    "item1Qty": 25,
    "item2": "Aluminum Casing",
    "item2Qty": 3,
    "item3": "Turbofuel",
    "item3Qty": 3000,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Nuke Nobelisk",
    "output": "Desc_NobeliskNuke_C",
    "outputQtyPerMin": 1,
    "item1": "Desc_NobeliskExplosive_C",
    "item1Qty": 5,
    "item2": "Encased Uranium Cell",
    "item2Qty": 20,
    "item3": "Smokeless Powder",
    "item3Qty": 10,
    "item4": "AI Limiter",
    "item4Qty": 6
  },
  {
    "recipe": "Rifle Ammo",
    "output": "Desc_CartridgeStandard_C",
    "outputQtyPerMin": 15,
    "item1": "Copper Sheet",
    "item1Qty": 3,
    "item2": "Smokeless Powder",
    "item2Qty": 2,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Explosive Rebar",
    "output": "Desc_Rebar_Explosive_C",
    "outputQtyPerMin": 1,
    "item1": "Desc_SpikedRebar_C",
    "item1Qty": 2,
    "item2": "Smokeless Powder",
    "item2Qty": 2,
    "item3": "Steel Pipe",
    "item3Qty": 2,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Cluster Nobelisk",
    "output": "Desc_NobeliskCluster_C",
    "outputQtyPerMin": 1,
    "item1": "Desc_NobeliskExplosive_C",
    "item1Qty": 3,
    "item2": "Smokeless Powder",
    "item2Qty": 4,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Nobelisk",
    "output": "Desc_NobeliskExplosive_C",
    "outputQtyPerMin": 1,
    "item1": "Black Powder",
    "item1Qty": 2,
    "item2": "Steel Pipe",
    "item2Qty": 2,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Smokeless Powder",
    "output": "Smokeless Powder",
    "outputQtyPerMin": 2,
    "item1": "Black Powder",
    "item1Qty": 2,
    "item2": "Heavy Oil Residue",
    "item2Qty": 1000,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "FICSMAS Wreath",
    "output": "FICSMAS Wreath",
    "outputQtyPerMin": 2,
    "item1": "FICSMAS Tree Branch",
    "item1Qty": 15,
    "item2": "FICSMAS Ornament Bundle",
    "item2Qty": 6,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Snowball",
    "output": "Desc_SnowballProjectile_C",
    "outputQtyPerMin": 1,
    "item1": "FICSMAS Actual Snow",
    "item1Qty": 3,
    "item2": null,
    "item2Qty": null,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "FICSMAS Wonder Star",
    "output": "FICSMAS Wonder Star",
    "outputQtyPerMin": 1,
    "item1": "FICSMAS Wreath",
    "item1Qty": 5,
    "item2": "Candy Cane",
    "item2Qty": 20,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Copper FICSMAS Ornament",
    "output": "Copper FICSMAS Ornament",
    "outputQtyPerMin": 1,
    "item1": "Red FICSMAS Ornament",
    "item1Qty": 2,
    "item2": "Copper Ingot",
    "item2Qty": 2,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Iron FICSMAS Ornament",
    "output": "Iron FICSMAS Ornament",
    "outputQtyPerMin": 1,
    "item1": "Blue FICSMAS Ornament",
    "item1Qty": 3,
    "item2": "Iron Ingot",
    "item2Qty": 3,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "FICSMAS Ornament Bundle",
    "output": "FICSMAS Ornament Bundle",
    "outputQtyPerMin": 1,
    "item1": "Copper FICSMAS Ornament",
    "item1Qty": 1,
    "item2": "Iron FICSMAS Ornament",
    "item2Qty": 1,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Red FICSMAS Ornament",
    "output": "Red FICSMAS Ornament",
    "outputQtyPerMin": 1,
    "item1": "FICSMAS Gift",
    "item1Qty": 1,
    "item2": null,
    "item2Qty": null,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Blue FICSMAS Ornament",
    "output": "Blue FICSMAS Ornament",
    "outputQtyPerMin": 2,
    "item1": "FICSMAS Gift",
    "item1Qty": 1,
    "item2": null,
    "item2Qty": null,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "FICSMAS Actual Snow",
    "output": "FICSMAS Actual Snow",
    "outputQtyPerMin": 2,
    "item1": "FICSMAS Gift",
    "item1Qty": 5,
    "item2": null,
    "item2Qty": null,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "FICSMAS Tree Branch",
    "output": "FICSMAS Tree Branch",
    "outputQtyPerMin": 1,
    "item1": "FICSMAS Gift",
    "item1Qty": 1,
    "item2": null,
    "item2Qty": null,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "FICSMAS Bow",
    "output": "FICSMAS Bow",
    "outputQtyPerMin": 1,
    "item1": "FICSMAS Gift",
    "item1Qty": 2,
    "item2": null,
    "item2Qty": null,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Candy Cane",
    "output": "Candy Cane",
    "outputQtyPerMin": 1,
    "item1": "FICSMAS Gift",
    "item1Qty": 3,
    "item2": null,
    "item2Qty": null,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Biomass (Leaves)",
    "output": "Desc_GenericBiomass_C",
    "outputQtyPerMin": 5,
    "item1": "Desc_Leaves_C",
    "item1Qty": 10,
    "item2": null,
    "item2Qty": null,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Biomass (Wood)",
    "output": "Desc_GenericBiomass_C",
    "outputQtyPerMin": 20,
    "item1": "Desc_Wood_C",
    "item1Qty": 4,
    "item2": null,
    "item2Qty": null,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Reinforced Iron Plate",
    "output": "Reinforced Iron Plate",
    "outputQtyPerMin": 1,
    "item1": "Iron Plate",
    "item1Qty": 6,
    "item2": "Screws",
    "item2Qty": 12,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Concrete",
    "output": "Concrete",
    "outputQtyPerMin": 1,
    "item1": "Desc_Stone_C",
    "item1Qty": 3,
    "item2": null,
    "item2Qty": null,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Screws",
    "output": "Screws",
    "outputQtyPerMin": 4,
    "item1": "Iron Rod",
    "item1Qty": 1,
    "item2": null,
    "item2Qty": null,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Cable",
    "output": "Cable",
    "outputQtyPerMin": 1,
    "item1": "Wire",
    "item1Qty": 2,
    "item2": null,
    "item2Qty": null,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Wire",
    "output": "Wire",
    "outputQtyPerMin": 2,
    "item1": "Copper Ingot",
    "item1Qty": 1,
    "item2": null,
    "item2Qty": null,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Copper Ingot",
    "output": "Copper Ingot",
    "outputQtyPerMin": 1,
    "item1": "Desc_OreCopper_C",
    "item1Qty": 1,
    "item2": null,
    "item2Qty": null,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Sweet Fireworks",
    "output": "Desc_Fireworks_Projectile_01_C",
    "outputQtyPerMin": 1,
    "item1": "FICSMAS Tree Branch",
    "item1Qty": 6,
    "item2": "Candy Cane",
    "item2Qty": 3,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Fancy Fireworks",
    "output": "Desc_Fireworks_Projectile_02_C",
    "outputQtyPerMin": 1,
    "item1": "FICSMAS Tree Branch",
    "item1Qty": 4,
    "item2": "FICSMAS Bow",
    "item2Qty": 3,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  },
  {
    "recipe": "Sparkly Fireworks",
    "output": "Desc_Fireworks_Projectile_03_C",
    "outputQtyPerMin": 1,
    "item1": "FICSMAS Tree Branch",
    "item1Qty": 3,
    "item2": "FICSMAS Actual Snow",
    "item2Qty": 2,
    "item3": null,
    "item3Qty": null,
    "item4": null,
    "item4Qty": null
  }
];
